### PR TITLE
Add categories to serverinfo

### PR DESCRIPTION
**Pull request by MiTonder**

### CODE REVIEW

**Comment by MiTonder** [comment]
How?

**Comment by MiTonder** [comment]
@trilleplay done

**Comment by MiTonder** [comment]
Understandable, but when there are channel and voice channel count + total, there should be a category

**Comment by MiTonder** [comment]
If i had more time, i would have made a bot counter

**Comment by AEnterprise** [comment]
this does make a large embed even larger, maybe it's worth looking into if we can't just roll all of these into a single field?

**Comment by MiTonder** [comment]
Understandable, if you can leave this open, i will Edit it when i come home

**Comment by MiTonder** [comment]
I think i have done everything to do with code. What more should i do. And is there anymore to do?

**Comment by AEnterprise** [comment]
i'll test it out later to make sure it works before merging

**Comment by MiTonder** [comment]
Nice

**Comment by MiTonder** [comment]
So, did it Work?

**Pull request merged**
